FROM python:3.12-slim

WORKDIR /app
ENV PYTHONPATH=/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY pipelines ./pipelines
COPY batch* ./

CMD ["python", "-u", "pipelines/run_model_retraining.py"]